---
- name: Register the host to scalelite
  become: true
  shell: >-
    docker exec scalelite-api 
    ./bin/rake servers:add[https://{{ hostname }}/bigbluebutton/api,{{ key }}]
    | grep -o "id:.*$" | grep -o "[^ ]*$"
  register: instance_id

- name: Enable hosts to scalelite
  become: true
  shell: >-
    docker exec scalelite-api 
    ./bin/rake servers:enable[{{ instance_id.stdout }}]
