---
- set_fact:
    desired_hostname: "{{ inventory_hostname }}"

# Устанавливаем ПО
- name: Install Prerequisites
  become: true
  apt:
    update_cache: yes
    name:
      - net-tools
      - language-pack-en
      - lsb-release
      - python3
      - python3-apt
      - python-apt
      - haveged
      - dbus
      - wget
    state: present
    force_apt_get: yes

# Проверяем локаль
- name: Change locale
  locale_gen:
    name: en_US.UTF-8
    state: present

- name: Configure firewall
  when: bigbluebutton_configure_firewall|bool
  include_tasks: firewall.yml

# Предупреждение пользователя
- name: Warn user
#  run_once: true
  debug:
    msg: >
        Ready to run wget -qO- https://ubuntu.bigbluebutton.org/bbb-install.sh | bash -s -- -v bionic-240 -s {{ full_name }} -a -w 
        This takes around 15 mns

# Установка BBB
- name: Launch install script
  become: true
  shell: wget -qO- https://ubuntu.bigbluebutton.org/bbb-install.sh | bash -s -- -v bionic-240 -s {{ full_name }} -a -w 

# Установка зависимостей
- name: Install dependencies
  become: true
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg2
      - software-properties-common
    state: present

- name: setting ssl
  include_tasks: ssl.yml

- name: Create cert
  include_tasks: certificate.yml

- name: Running setip
  become: true
  shell: bbb-conf --setip {{ full_name }}

# Изменение настроек webrtc
- name: Modify webrtc value
  become: true
  command: yq w -i /usr/local/bigbluebutton/bbb-webrtc-sfu/config/default.yml {{ item.key }} "{{ item.value }}"
  loop: "{{ bigbluebutton_webrtc|dict2items }}"

# Копирование презентации по умолчанию
- name: Change default presentation
  become: true
  copy:
    src: files/default.pdf
    dest: /var/www/bigbluebutton-default/default.pdf
    mode: +r

- name: Change bigbluebutton_properties
  become: true
  copy:
    src: files/bigbluebutton.properties
    dest: /usr/share/bbb-web/WEB-INF/classes/bigbluebutton.properties
    mode: +r 

- name: Configure config
  include_tasks: modify.yml

- name: restart bigbluebutton
  become: true
  command: bbb-conf --restart