- name: Modify meteor_setting
  become: true
  lineinfile:
    regexp: '    mirrorOwnWebcam: false'
    line: "    mirrorOwnWebcam: true"
    path: /usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml
    state: present

- name: Modify meteor_setting
  become: true
  lineinfile:
    regexp: '    hidePresentation: false'
    line: "    hidePresentation: true"
    path: /usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml
    state: present

- name: Modify meteor_setting
  become: true
  lineinfile:
    regexp: '    autoSwapLayout: false'
    line: "    autoSwapLayout: true"
    path: /usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml
    state: present

- name: Modify meteor_setting
  become: true
  lineinfile:
    regexp: '    autoJoin: true'
    line: "    autoJoin: false"
    path: /usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml
    state: present

- name: Modify meteor_setting
  become: true
  lineinfile:
    regexp: '    listenOnlyMode: true'
    line: "    listenOnlyMode: false"
    path: /usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml
    state: present

- name: Modify meteor_setting
  become: true
  lineinfile:
    regexp: '    skipCheck: false'
    line: "    skipCheck: true"
    path: /usr/share/meteor/bundle/programs/server/assets/app/config/settings.yml
    state: present