- name: 'Copy key'
  become: true
  ansible.builtin.copy:
    content: |
      -----BEGIN RSA PRIVATE KEY-----
      ***
      -----END RSA PRIVATE KEY-----
    dest: '{{ ssl_certificate_key }}'

- name: 'Copy cert'
  become: true
  ansible.builtin.copy:
    content: |
      -----BEGIN CERTIFICATE-----
      ***
      -----END CERTIFICATE-----
    dest: '{{ ssl_certificate }}'
